### ISSUE TITLE
Workaround sticky buttons in webviews

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/ehealth-bootstrap#17]
According to https://github.com/twbs/bootstrap/pull/13049 (via https://github.com/twbs/bootstrap/issues/12832) `:hover` styles aren't removed correctly in some mobile browsers.

In Nutsurv, we workaround this by resetting `:hover` (and `:focus`) and applying its style on `:active`:

``` css
  /* Workaround "sticky hover" bug */                                                                                                                           
  .btn-default:hover, .btn-default:focus  {                                                                                                                               
    background-color: white;                                                                                                                                              
  }                                                                                                                                                                       
  .btn-default:active {                                                                                                                                                   
    background-color: #e0e0e0;                                                                                                                                            
  } 
```

Perhaps this is another candidate for a mobile-specific theme?
