### ISSUE TITLE
Style required inputs

### ISSUE THREAD

**Issue by codebeige** [eHealthAfrica/ehealth-bootstrap#8]
I think we could make use of a harmonized way of marking required inputs across applications. As this is not done by Bootstrap per se, not sure if this would go here, though.

@bnvk @tthew Any thoughts on that?

**Comment by codebeige** [comment]
If we go with the classical asterisk approach, this could be a starting point:

``` css
.form-group.required {
  label:after {
    content: "  \f069";
    font-family: FontAwesome;
    font-size: .4em;
    vertical-align: super;
  }
}
```

Looks something like this:

![bildschirmfoto 2015-04-20 um 17 06 51](https://cloud.githubusercontent.com/assets/91858/7233168/ffc9935a-e77f-11e4-86c4-5ec0e14eafea.png)
